package Security.DAO;

import DTO.PersonDTO;
import Model.Person;
import jakarta.persistence.EntityManager;

import java.util.List;

public class PersonDAO extends DAO<PersonDTO, Person> {

    //Singleton
    private static PersonDAO instance;
    private PersonDAO(){}
    public static PersonDAO getInstance(){
        if(instance == null){
            instance = new PersonDAO();
        }
        return instance;
    }

    @Override
    public Person create(PersonDTO personDTO) {
        try (EntityManager em = emf.createEntityManager()){
            em.getTransaction().begin();
            Person person = new Person(personDTO);

            em.persist(person);
            em.getTransaction().commit();
            //Find the autogenerated id for the person and return it to set it in the personDTO
            List<Person> persons = em.createQuery("SELECT p FROM Person p", Person.class).getResultList();
            Person createdPerson = persons.get(persons.size()-1);
            return createdPerson;
        }    }

    @Override
    public Person update(PersonDTO personDTO) {
        try (EntityManager em = emf.createEntityManager()){
            em.getTransaction().begin();
            Person person = em.find(Person.class, personDTO.id);
            person.setName(personDTO.name);
            person.setEmail(personDTO.email);
            person.setRole(personDTO.role);
            em.merge(person);
            em.getTransaction().commit();
            return person;
        }    }
}
